"""Add audio_responses

Revision ID: 1b2c1eb07d08
Revises: 
Create Date: 2026-01-24 12:38:48.307204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2c1eb07d08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('evaluation_status', sa.String(length=20), nullable=True))
    op.add_column('interview_sessions', sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'evaluated_at')
    op.drop_column('interview_sessions', 'evaluation_status')
    # ### end Alembic commands ###
